# -- Hauptmenü --
# Das Hauptmenü wird in der Kopfzeile oben auf der Seite angezeigt.


[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Smponi"
  weight = 40

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/smponias-p/"
  weight = 50


# -- Fußzeilenmenü --

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Autoren"
   pageRef = "authors"
   weight = 20
